# Stack:       pihole_doh
# Description: Pi-hole with DoH (cloudflared) behind Treafik
# Author:      BornToBeRoot
# Version:     1.0.0
# Updated:     2024-05-11
# Source:      https://github.com/BornToBeRoot/docker-compose


version: "3"

# More info at
# - https://hub.docker.com/r/visibilityspots/cloudflared
services:
  cloudflared:
    image: "${CLOUDFLARED_IMAGE}"
    container_name: "cloudflared"
    restart: always
    networks:
      dns_network:
        ipv4_address: 10.0.0.2
    environment:
      UPSTREAM1: ${CLOUDFLARED_DNS_UPSTREAM1}
      UPSTREAM2: ${CLOUDFLARED_DNS_UPSTREAM2}
    dns:
      # Local is required in docker
      - 127.0.0.1
      # Gateway or public dns
      - ${FALLBACK_DNS_RESOLVER}

# More info at
# - https://hub.docker.com/r/pihole/pihole/
# - https://github.com/pi-hole/docker-pi-hole/
# - https://docs.pi-hole.net/
  pihole:
    image: "${PIHOLE_IMAGE}"
    container_name: "pihole"
    restart: always    
    networks:
      dns_network:
        ipv4_address: 10.0.0.3
      traefik_proxy:
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      FTLCONF_LOCAL_IPV4: ${DOCKER_HOST_IP}
      TZ: ${PIHOLE_TIMEZONE}
      WEBPASSWORD: ${PIHOLE_PASSWORD}
      VIRTUAL_HOST: ${TRAEFIK_FQDN}
      DNSMASQ_LISTENING: 'all'
      PIHOLE_DNS_: '10.0.0.2#5054'
      DNSSEC: ${PIHOLE_DNSSEC_ENABLED}
      DNS_BOGUS_PRIV: ${PIHOLE_DNS_BOGUS_PRIV_ENABLED}
      DNS_FQDN_REQUIRED: ${PIHOLE_DNS_FQDN_REQUIRED_ENABLED}
      REV_SERVER: ${PIHOLE_REV_SERVER_ENABLED}
      REV_SERVER_DOMAIN: ${PIHOLE_REV_SERVER_DOMAIN}
      REV_SERVER_TARGET: ${PIHOLE_REV_SERVER_TARGET}
      REV_SERVER_CIDR: ${PIHOLE_REV_SERVER_CIDR}
      QUERY_LOGGING: ${PIHOLE_QUERY_LOGGING_ENABLED}
      FTLCONF_PRIVACYLEVEL: ${PIHOLE_PRIVACYLEVEL}
      WEBTHEME: ${PIHOLE_WEBTHEME}
      WEBUIBOXEDLAYOUT: ${PIHOLE_WEBUIBOXEDLAYOUT}
      TEMPERATUREUNIT: ${PIHOLE_TEMPERATURE_UNIT}
    volumes:
       - "./data/etc/pihole/:/etc/pihole/"
       - "./data/etc/dnsmasq.d/:/etc/dnsmasq.d/"
    dns:
      # Local is required in docker
      - 127.0.0.1
      # Gateway or public dns
      - ${FALLBACK_DNS_RESOLVER}
    labels:
      - "traefik.enable=${TRAEFIK_ENABLED}"
      # 80/tcp redirected to 443/tcp via traefik
      - "traefik.http.routers.pihole.rule=Host(`${TRAEFIK_URI}`)"
      - "traefik.http.routers.pihole.entrypoints=websecure"
      - "traefik.http.routers.pihole.tls.certresolver=${TRAEFIK_TLS_CERT_RESOLVER}"
      - "traefik.http.routers.pihole.tls=${TRAEFIK_TLS_ENABLED}"
      - "traefik.http.routers.pihole.service=pihole"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      # Use traefik proxy network
      - "traefik.docker.network=traefik_proxy"

networks:
  dns_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/29
  traefik_proxy:
    external:
      name: traefik_proxy
