# Stack:       mosquitto
# Description: Mosquitto is an open source MQTT broker.
# Author:      BornToBeRoot
# Version:     1.0.0
# Updated:     2024-05-11
# Source:      https://github.com/BornToBeRoot/docker-compose

version: "3"

services:
  mqtt:
    container_name: "mosquitto"
    image: "eclipse-mosquitto:2"
    restart: always
    ports:
      - "1883:1883/tcp"
      - "9001:9001/tcp"
    volumes:
      - "./data/mosquitto/config:/mosquitto/config"
      - "./data/mosquitto/data:/mosquitto/data"
